Added advanced codeql, updated brainfuck workflow
Updated brainfuck workflow trying to resolve error

diff --git a/.github/workflows/brainfuck.yaml b/.github/workflows/brainfuck.yaml
--- a/.github/workflows/brainfuck.yaml
+++ b/.github/workflows/brainfuck.yaml
@@ -35,7 +35,7 @@ jobs:
 
       - name: Run Brainfuck files
         run: |
-          for file in b/brainfuck/**/*.b; do
+          for file in $(find b/brainfuck -type f \( -name "*.bf" -o -name "*.b" \)); do
             echo "Running $file"
-            echo "A" | bf "$file" || { echo "Error in $file"; exit 1; }
+            echo "A" | beef "$file" || { echo "Error in $file"; exit 1; }
           done
